### ISSUE TITLE
Snap package ready and with the latest version

### ISSUE THREAD

**Issue by soumyaDghosh** [flathub/com.github.hugolabe.Wike#10]
Hello, I packaged your app as snap, from the latest version, would you like to have it?

**Comment by hugolabe** [comment]
Hi @soumyaDghosh
Flatpak is the only official package for Wike and the only one I maintain. Other packaging formats can be created and maintained by the community.

But, from what I have seen, Wike is [available](https://snapcraft.io/wike) in the Snap Store. Isn't it?
