### ISSUE TITLE
No need for --filesystem=home

### ISSUE THREAD

**Issue by liferooter** [flathub/com.github.hugolabe.Wike#9]
It looks like the application doesn't need to have `--filesystem=home` permission. I suggest to remove the permission for better security and to follow principle of least priviledge.

**Comment by hugolabe** [comment]
This is necessary for the app to work properly.
Look at [this](https://github.com/hugolabe/Wike/pull/129)

**Comment by liferooter** [comment]
There are XDG Desktop Portals to do so without such security holes

**Comment by hugolabe** [comment]
The GTK portal already allows you to access Home through file dialogues. However, in this case, the print dialog is handled by WebKit through a Print Operation. I think the problem I show in the Screenshot can be related to the way WebKit handles file paths.
